#!/bin/bash

name=boil_query

print_usage(){
cat << EOF     
Usage:                      
        $name [--template-dir] 
                Query boil config
        -h, --help
                prints this help message
EOF
}

#-o f: <- expects argument for f
#-o h <- doesn't expect argument for h
OPTS=`getopt -o ht --long help,template-dir -n "$name"  -- "$@"`
if [ $? != 0 ] ; then echo "Failed to parse args" >&2 ; exit 1 ; fi

eval set -- "$OPTS"

template_dir(){
    set_config_dir() {
        config_dir="$HOME/.config"
        if [[ -d "$XDG_CONFIG_HOME" ]]; then
        config_dir="$XDG_CONFIG_HOME"
        fi
    }


    if [[ -d "$BOIL_TEMPLATE_DIR" ]]
    then
        template_dir="$(realpath $BOIL_TEMPLATE_DIR)"
    else
        set_config_dir
        template_dir="$config_dir/boil/templates"
    fi

    printf "$template_dir\n"
}

while true;do
case "$1" in
-h|--help)
    print_usage
    exit 0
    ;;
-t|--template-dir)
    template_dir
    exit
    shift
    ;;
--)
    shift
    break
    ;;
*)
    break
    ;;
esac
shift
done

print_usage
